//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// SwaySensorA.rc で使用
//
#define IDC_MYICON                      2
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_SWAYSENSORA                 107
#define IDI_SMALL                       108
#define IDC_SWAYSENSORA                 109
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_CAMMAIN              138
#define IDD_DIALOG_TASKSET              139
#define IDB_ANALYST                     140
#define IDB_CAMERACOM                   141
#define IDB_CLERK                       142
#define IDB_COMCLIENT                   143
#define IDB_MANAGER                     144
#define IDB_PLAYER                      145
#define IDB_PR                          146
#define IDB_RIOCOM                      147
#define IDB_BITMAP_BLUE                 148
#define IDB_BITMAP_GRAY                 149
#define IDB_BITMAP_GREEN                150
#define IDB_BITMAP_LTBLUE               151
#define IDB_BITMAP_MAGENTA              152
#define IDB_BITMAP_RED                  153
#define IDB_BITMAP_WHITE                154
#define IDB_BITMAP_YELLOW               155
#define IDC_BUTTON_RESET                1000
#define IDC_STATIC_GBX_IMG_RAW          1000
#define IDC_STATIC_VAL_FRAME            1001
#define IDC_STATIC_TITLE_GRV_X_TITLE    1002
#define IDC_CHECK_TASK_OPTION1          1003
#define IDC_STATIC_TITLE_GRV_Y          1003
#define IDC_CHECK_TASK_OPTION2          1004
#define IDC_STATIC_TITLE_INC_X          1004
#define IDC_RADIO_TASK_FUNC1            1005
#define IDC_RADIO_TASK_FUNC2            1006
#define IDC_STATIC_TITLE_INC_X_DEG      1006
#define IDC_RADIO_TASK_FUNC3            1007
#define IDC_RADIO_TASK_FUNC4            1008
#define IDC_STATIC_TITLE_FPS            1008
#define IDC_RADIO_TASK_FUNC5            1009
#define IDC_STATIC_TITLE_PROC_TIME      1009
#define IDC_RADIO_TASK_FUNC6            1010
#define IDC_STATIC_CMD_FRAME            1010
#define IDC_STATIC_TASK_FUNC            1011
#define IDC_STATIC_TITLE_H1             1011
#define IDC_STATIC_TASK_ITEM            1012
#define IDC_STATIC_GBX_IMG_MASK         1012
#define IDC_RADIO_TASK_ITEM1            1013
#define IDC_SLIDER_H1_LOW               1013
#define IDC_RADIO_TASK_ITEM2            1014
#define IDC_STATIC_TITLE_IMG_GRAB_TIME  1014
#define IDC_RADIO_TASK_ITEM3            1015
#define IDC_STATIC_VAL_H1_LOW           1015
#define IDC_RADIO_TASK_ITEM4            1016
#define IDC_SLIDER_H1_UPP               1016
#define IDC_RADIO_TASK_ITEM5            1017
#define IDC_STATIC_VAL_H1_UPP           1017
#define IDC_RADIO_TASK_ITEM6            1018
#define IDC_SLIDER_S1_LOW               1018
#define IDC_STATIC_TASKNAME             1019
#define IDC_STATIC_TITLE_S1             1019
#define IDC_EDIT_TASK_VAL1              1020
#define IDC_STATIC_VAL_S1_LOW           1020
#define IDC_EDIT_TASK_VAL2              1021
#define IDC_SLIDER_S1_UPP               1021
#define IDC_EDIT_TASK_VAL3              1022
#define IDC_STATIC_VAL_S1_UPP           1022
#define IDC_EDIT_TASK_VAL4              1023
#define IDC_SLIDER_V1_LOW               1023
#define IDC_EDIT_TASK_VAL5              1024
#define IDC_STATIC_TITLE_V1             1024
#define IDC_EDIT_TASK_VAL6              1025
#define IDC_STATIC_VAL_V1_LOW           1025
#define IDC_SLIDER_V1_UPP               1026
#define IDC_STATIC_TASK_VAL             1027
#define IDC_STATIC_VAL_V1_UPP           1027
#define IDC_STATIC_TASK_VAL1            1028
#define IDC_SLIDER_H2_LOW               1028
#define IDC_STATIC_TASK_VAL2            1029
#define IDC_STATIC_TITLE_H2             1029
#define IDC_STATIC_TASK_VAL3            1030
#define IDC_STATIC_VAL_H2_LOW           1030
#define IDC_STATIC_TASK_VAL4            1031
#define IDC_STATIC_TASK_VAL5            1032
#define IDC_SLIDER_H2_UPP               1032
#define IDC_STATIC_TASK_VAL6            1033
#define IDC_STATIC_VAL_H2_UPP           1033
#define IDC_LIST_TASK                   1034
#define IDC_SLIDER_S2_LOW               1034
#define IDC_STATIC_TITLE_S2             1035
#define IDC_STATIC_VAL_S2_LOW           1036
#define IDC_SLIDER_S2_UPP               1037
#define IDC_STATIC_VAL_S2_UPP           1038
#define IDC_SLIDER_V2_LOW               1039
#define IDC_STATIC_TITLE_V2             1040
#define IDC_STATIC_VAL_V2_LOW           1041
#define IDC_SLIDER_V2_UPP               1042
#define IDC_STATIC_VAL_V2_UPP           1043
#define IDC_STATIC_MASK1                1044
#define IDC_STATIC_MASK2                1045
#define IDC_STATIC_NOISEFILTER          1046
#define IDC_SLIDER_NOISEFILTER1         1047
#define IDC_STATIC_VAL_NOISEFILTER1     1048
#define IDC_COMBO_NOISEFILTER1          1049
#define IDC_CHECK_CURSOR                1050
#define IDC_CHECK_ROI                   1051
#define IDC_COMBO_NOISEFILTER2          1052
#define IDC_COMBO_IMG                   1053
#define IDC_SLIDER_NOISEFILTER2         1054
#define IDC_STATIC_GBX_CAMERA_EXPOSURE  1055
#define IDC_STATIC_CAMERA_EXPOSURE      1055
#define IDC_STATIC_VAL_NOISEFILTER2     1056
#define IDC_STATIC_ROI                  1057
#define IDC_SLIDER_CAMERA_EXPOSURE      1059
#define IDC_STATIC_VAL_CAMERA_EXPOSURE  1060
#define IDC_SLIDER_CAMERA_EXPOSURE2     1061
#define IDC_SLIDER_ROI                  1061
#define IDC_STATIC_GRV_X1               1062
#define IDC_STATIC_GRV_X2               1063
#define IDC_STATIC_GRV_Y1               1064
#define IDC_STATIC_GRV_Y2               1065
#define IDC_STATIC_INC_X                1066
#define IDC_STATIC_INC_Y                1067
#define IDC_STATIC_INC_X_DEG            1068
#define IDC_STATIC_INC_Y_DEG            1069
#define IDC_STATIC_FPS                  1070
#define IDC_STATIC_PROC_TIME            1071
#define IDC_STATIC_IMG_GRAB_TIME        1072
#define IDC_STATIC_VAL_ROI              1073
#define IDC_BUTTON_CAM_START            2002
#define IDC_BUTTON_CURSOR_L             2028
#define IDC_BUTTON_CAM_STOP             2031
#define IDC_BUTTON_CURSOR_R             2032
#define IDC_BUTTON_CURSOR_U             2033
#define IDC_BUTTON_CURSOR_D             2034
#define IDC_STATIC_IMAGE_MASK           2040
#define IDC_BUTTON_SAVE                 2041
#define IDC_STATIC_IMAGE_RAW            2045
#define IDC_BUTTON_SET                  2053
#define IDC_BUTTON_IMG_PROC             2057
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
